spring:
  ## Application
  application:
    name: TodoList
  ## Database
  datasource:
    url: jdbc:mysql://localhost:3307/todo
    username: bloguser
    password: blogpw
    hikari:
      maximum-pool-size: 10     # ???? connection ? ???? Pool ? ????? ?? Connection ??
      minimum-idle: 10          #  DBCP ?? ???? ?? ??(Idle) ???? ?, App ? ??? ? ?? ??? ? ?? ???? ?? ??? ??
      idle-timeout: 600000      # ?? ???? ???? ?? (Idle ???) Connect ? Pool ?? ???? ?? ??, 10?
      connection-timeout: 30000 # Application ?  DBCP ?? Connection ? ??? ? ??? ? ?? ?? ??, 30?
      max-lifetime: 1800000     # DBCP ?? Connection ? ??? ? ?? ?? ??, 30?

  ## Hibernate
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

## Tomcat
server:
  port: 8090
  tomcat:
    threads:
      max: 200                # ??? ? ?? thread ? ? ??
      min-spare: 10           # ?? ??? ???? (idle) Thread ? ??
    max-connections: 8192     # ?? ??? Connection ? ? ??
    connection-timeout: 20000 # ?????? ?? ???? ??? ? ?? ??, 20?
    accept-count: 100         # ?? Connection ? ? ?? , max-connections ? ?? ???, Queue ? ?? Connection ? ??
    keep-alive-timeout: 100   # ??? ?????? ??? ??? ???? ???? HTTP ??? ???? ?? ??, 100?

## ???
jasypt:
  encryptor:
    key:

## Logging
logging:
  level:
    root: info
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"